/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author pedro
 */
public class ConfirmarEdicaoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfirmarEdicaoView
     */
    public ConfirmarEdicaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNao = new javax.swing.JButton();
        btnSim = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setTitle("Confirmar Edição");
        setMaximumSize(new java.awt.Dimension(370, 214));
        setMinimumSize(new java.awt.Dimension(370, 214));
        setPreferredSize(new java.awt.Dimension(370, 214));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNao.setText("Não");
        getContentPane().add(btnNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        btnSim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSim.setText("Sim");
        getContentPane().add(btnSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label.setText("Deseja realmente editar esse Usuário?");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 35, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNao;
    private javax.swing.JButton btnSim;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
