/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JTextField;

/**
 *
 * @author pedro
 */
public class VisualizarUsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarUsuarioView
     */
    public VisualizarUsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgUsuario = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtDataCriacao = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        imgUsuario1 = new javax.swing.JLabel();
        txtTotalNotificaoes = new javax.swing.JTextField();
        txtNotificacoesLidas = new javax.swing.JTextField();
        lblNotificacoesLidas = new javax.swing.JLabel();
        lblTipoNotificacoes = new javax.swing.JLabel();

        imgUsuario.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario-medio.png"))); // NOI18N

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("<nome-usuario>");
        setMaximumSize(new java.awt.Dimension(416, 492));
        setMinimumSize(new java.awt.Dimension(416, 492));
        setPreferredSize(new java.awt.Dimension(416, 492));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTipo.setEnabled(false);
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, 31));

        txtDataCriacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDataCriacao.setEnabled(false);
        getContentPane().add(txtDataCriacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 180, 31));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo:");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        lblDataCriacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataCriacao.setText("Data de Criação:");
        getContentPane().add(lblDataCriacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setEnabled(false);
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 373, 31));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        imgUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        imgUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario-medio.png"))); // NOI18N
        getContentPane().add(imgUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        txtTotalNotificaoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalNotificaoes.setEnabled(false);
        getContentPane().add(txtTotalNotificaoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, 31));

        txtNotificacoesLidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNotificacoesLidas.setEnabled(false);
        getContentPane().add(txtNotificacoesLidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 180, 31));

        lblNotificacoesLidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNotificacoesLidas.setText("Notificações Lidas:");
        getContentPane().add(lblNotificacoesLidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        lblTipoNotificacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipoNotificacoes.setText("Total de Notificações:");
        getContentPane().add(lblTipoNotificacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtDataCriacao() {
        return txtDataCriacao;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public JTextField getTxtNotificacoesLidas() {
        return txtNotificacoesLidas;
    }

    public JTextField getTxtTipo() {
        return txtTipo;
    }

    public JTextField getTxtTotalNotificaoes() {
        return txtTotalNotificaoes;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgUsuario;
    private javax.swing.JLabel imgUsuario1;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNotificacoesLidas;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoNotificacoes;
    private javax.swing.JTextField txtDataCriacao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNotificacoesLidas;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTotalNotificaoes;
    // End of variables declaration//GEN-END:variables
}
